# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='added',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='job',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='NONE', max_length=140),
            preserve_default=False,
        ),
    ]
